const obj =  {
    empId:'',
    empName:'',
    memBerId:'',
    email:'',
    emailUniqId:'',
    crmRights:{
    crmDashboard:{
           value:false,
           rights:[]
    },
    crmEmployee:{
           value:false,
           items:{
               crmDashboard1:{
                   value:false,
                  rights:[]
               },
               crmEmployeeTarget1:{
                   value:false,
                   rights:[]
               },
               crmMemberCalls1:{
                   value:false,
                   rights:[]
               },crmSalesCall1:{
                   value:false,
                   rights:[]
               },crmServicesRateCard1:{
                   value:false
               }
           }
    },
    crmTrainer:{
           value:false,
           items:{
               superRight:{
                   dailybatchAttendance:[],
                   monthlyReport:[],
                   clientAttendanceReg:[]
               },    
               crmLiveClasses1:{
                   value:false
               },
               crmAllBatches1:{
                   value:false
               },
               crmPtClasses1:{
                   value:false
               },
               crmTtcClasses:{
                   value:false
               },
               crmAllMembers1:{
                   value:false
               }
           }
    },
    crmLeads:{
        value:false,
        items:{
            superRight:{
                addOn:[],
                delete:[],
                edit:[]
            },
            crmAllEnquiry1:{
                value:false,
            },
            crmAppointment1:{
                value:false,
            },
            crmTrialUpdate1:{
                value:false,
            },
            crmProspects1:{
                value:false,
            },
            crmCallsReports1:{
                value:false,
            },
            crmColdEnquires1:{
                value:false,
            }
        }
    },
    crmCientManagment:{
        value:false,
        items:{
            superRight:{
                delete:[],
                edit:[],
                status:[],
                profile:[]
            },
            crmAllClients1:{
                value:false,
            },
            crmActiveClients1:{
                value:false,
            },
            crmRenewalsClient1:{
                value:false,
            },
            crmRenewedClients1:{
                value:false,
            },
            crmLeftClients1:{
                value:false,
            },
            crmClientSupport1:{
                value:false,
            }
        }
    },
    crmMarketing:{
        value:false,
        items:{
            superRight:{
                addOn:[],
                delete:[],
                edit:[],
                status:[],
            },
            crmEmailMarketing1:{
                value:false
            },
            crmSmsMarketing1:{
                value:false
            },
            crmPushMarketing1:{
                value:false
            },
            crmBulkMailerData1:{
                value:false
            },
            crmBulkCallingData1:{
                value:false
            },
            crmCustomerReview1:{
                value:false
            },
            crmOffersMaster1:{
                value:false
            }
        }
    },
    crmFitness:{
        value:false,
        items:{
              superRight:{
                addOn:[],
                delete:[],
                edit:[],
                access:[],
            },
            crmFitnessGoal:{
                value:false,
            }
         }
    }
    }   
   }

export default obj